name: build-on-chrome
on:
  push:
    paths:
      - '**.js'
      - 'example/index.html'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Chrome
      run: |
        npm i
        npm run test.Chrome
